data:extend(
{
   {
    type = "fluid",
    name = "copper-sulfate-solution",
    icon = "__corrundum__/graphics/icons/fluid/copper-sulfate-solution.png",
    subgroup = "sulfur",
    default_temperature = 21,
    max_temperature = 100,
    heat_capacity = "4.184kJ",
    base_color = {0.22, 0.1, 0.9},
    flow_color = {0.22, 0.4, 1.35},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "iron-sulfate-solution",
    icon = "__corrundum__/graphics/icons/fluid/iron-sulfate-solution.png",
    subgroup = "sulfur",
    default_temperature = 21,
    max_temperature = 100,
    heat_capacity = "4.184kJ",
    base_color = {0.2, 0.8, 0.63},
    flow_color = {0.2, 1.0, 0.8},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "mixed-sulfate-solution",
    icon = "__corrundum__/graphics/icons/fluid/mixed-sulfate-solution.png",
    subgroup = "sulfur",
    default_temperature = 21,
    max_temperature = 100,
    heat_capacity = "4.184kJ",
    base_color = {0.2, 0.5, 0.7},
    flow_color = {0.2, 0.8, 1.0},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "sulfuric-acid-dilute",
    icon = "__corrundum__/graphics/icons/fluid/sulfuric-acid-dilute.png",
    subgroup = "sulfur",
    default_temperature = 21,
    max_temperature = 100,
    heat_capacity = "4.184kJ",
    base_color = {0.73, 0.73, 0.57},
    flow_color = {1.0, 1.0, 0.8},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "hydrogen-sulfide",
    icon = "__corrundum__/graphics/icons/fluid/hydrogen-sulfide.png",
    subgroup = "sulfur",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "34.2J",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "sulfur-dioxide",
    icon = "__corrundum__/graphics/icons/fluid/sulfur-dioxide.png",
    subgroup = "sulfur",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "39.84J",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = true,
   },
   {
      type = "fluid",
      name = "carbon-dioxide",
      icon = "__corrundum__/graphics/icons/fluid/carbon-dioxide.png",
      subgroup = "sulfur",
      default_temperature = 21,
      max_temperature = 3000,
      heat_capacity = "840J",
      base_color = {0, 0.15, 0.4},
      flow_color = {0, 0.35, 0.7},
      auto_barrel = false,
   }
}

)